# Site settings
title:          David Notes
description:    "Personal toughts, book reviews, and rages"
baseurl:        ""
url:            "https://blog.davidomar.me"

# Author
author:
  name:         David Omar Flores Chávez
  url:          https://davidomar.me
  email:        davidomarfch@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5
